isDebug: true
users:
  - login: vasyaod
    schedule:
      mon:
        - start: 10:20
          end: 11:20
      tue:
        - start: 10:20
          end: 11:20
      wed:
        - start: 10:20
          end: 11:20
      thu:
        - start: 10:20
          end: 11:20
      fri:
        - start: 10:20
          end: 11:20
      sat:
        - start: 10:20
          end: 11:20
      sun:
        - start: 10:20
          end: 11:20