isDebug: true                # If the flag is true the program will not kill a user just print stdout message
users:
  - login: user              # System login / user name
    timeLimit: 180           # Daily time limit (minutes)
    schedule:
      mon:
        - start: 00:00
          end: 23:59
      tue:
        - start: 00:00
          end: 23:59
      wed:
        - start: 00:00
          end: 23:59
      thu:
        - start: 00:00
          end: 23:59
      fri:
        - start: 00:00
          end: 23:59
      sat:
        - start: 00:00
          end: 23:59
      sun:
        - start: 00:00
          end: 23:59
