commands:
  # Command checks user in a system.
  # The requirement is that the command should return 0 exit code if a user is in a system otherwise
  # return any another code.
  check: "who | grep %s | [ $(wc -c) -ne 0 ]"

  # Doesn't work yet
  message: "echo 'This is stub which is not sent a message anywhere'"

  # Command which should kill/logout a user
  kill: "skill -KILL -u %s"

users:
  - login: dummy-user             # System login / user name
    timeLimit: 180                # Daily time limit (minutes)
    schedule:
      mon:
        - start: 00:00
          end: 23:59
      tue:
        - start: 00:00
          end: 23:59
      wed:
        - start: 00:00
          end: 23:59
      thu:
        - start: 00:00
          end: 23:59
      fri:
        - start: 00:00
          end: 23:59
      sat:
        - start: 00:00
          end: 23:59
      sun:
        - start: 00:00
          end: 23:59
