commands:
  # Command checks user in a system.
  # The requirement is that the command should return 0 exit code if a user is in a system otherwise
  # return any another code.
  #
  # Template params
  #   {0} is user name/login
  check: "who | grep {0} | [ $(wc -c) -ne 0 ]"

  # Can be used following command
  # notify-send 'Hello world!' 'This is an example notification.' --icon=dialog-information
  # Taken from here https://wiki.archlinux.org/index.php/Desktop_notifications
  # Example
  # message: "notify-send 'Your time is mostly up' 'You have only 5 minutes before logout.' --icon=dialog-information"
  #
  # Template params
  #   {0} is user name/login
  message: "echo 'This is stub which is not sent a message anywhere'"

  # Command which should kill/logout a user
  #
  # Template params
  #   {0} is user name/login
  kill: "skill -KILL -u {0}"

# This app keep all state in memory but periodically can unload some information to file.
# Basically it is one of ways to et information about users
stateFilePath: /var/run/parental-control/state

# The param works if parental-control-web is set up
httpPort: 8090

# PAth to http static content, like html pages and JS scripts
httpStaticPath: /usr/share/parental-control

users:
  - login: dummy-user             # System login / user name
    timeLimit: 180                # Daily time limit (minutes)
    noticePeriod: 5               # Notice period is the time period between the sending message and the killing of a user (minutes)
    schedule:
      mon:
        - start: 00:00
          end: 23:59
      tue:
        - start: 00:00
          end: 23:59
      wed:
        - start: 00:00
          end: 23:59
      thu:
        - start: 00:00
          end: 23:59
      fri:
        - start: 00:00
          end: 23:59
      sat:
        - start: 00:00
          end: 23:59
      sun:
        - start: 00:00
          end: 23:59