on: [push]
name: build
jobs:
  runhaskell:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          #ghc-version: '8.8.3' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defalts to 'latest'
          enable-stack: true
          stack-version: 'latest'

      - name: Cache of Stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}

      - run: cd schedule-daemon && stack build --test --copy-bins
      - run: cd web-ui && npm install && npm build
      - run: sudo apt-get update && sudo apt-get -y install alien
      - run: ./build-deb                       # build package for deamon
      - run: ./build-deb-web                   # build package for web interface
      - uses: actions/upload-artifact@v2
        with:
          name: parental-control
          path: |
            dist/*.rpm
            dist/*.deb