on: [push]
name: build
jobs:
  
  build-windows-verson:
    name: Windows build
    runs-on: windows-2022
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Cache of Stack
        uses: actions/cache@v2
        with:
          path: ~\AppData\Roaming\stack
          key: ${{ runner.os }}
      - run: cd schedule-daemon && stack build --test --copy-bins
      - run: cd web-ui && npm install && npm run build
      - name: Prepare files for contribution
        shell: cmd
        run: .\build-windows.bat
      - name: Create installer
        uses: joncloud/makensis-action@v3.6
        with:
          arguments: "/V3"
          script-file: "parental-control.nsi"
      - uses: actions/upload-artifact@v2
        with:
          name: parental-control-windows
          path: |
            parental-control-setup.exe


      - uses: actions/upload-artifact@v2
        with:
          name: parental-control-windows-exe
          path: |
            parental-control.exe

      - uses: actions/upload-artifact@v2
        with:
          name: parental-control-web-exe
          path: |
            parental-control-web.exe
            
      - name: Assets Uploading # https://gist.github.com/joncardasis/e6494afd538a400722545163eb2e1fa5
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'Automation'
          git config --global user.email 'your-username@users.noreply.github.com'
          git checkout --orphan windows-assets
          git rm -rf .
          git add parental-control-setup.exe
          git commit -m "Windows assets"
          git push -f origin windows-assets