on: [push]
name: build
jobs:
  build-linux-verson:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: wget -qO- https://get.haskellstack.org/ | sh
      #- uses: actions/setup-haskell@v1.1
      #  with:
      #    #ghc-version: '8.8.3' # Exact version of ghc to use
      #    # cabal-version: 'latest'. Omitted, but defalts to 'latest'
      #    enable-stack: true
      #    stack-version: 'latest'

      - name: Cache of Stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}

      - run: cd schedule-daemon && stack build --test --copy-bins
      - run: cd web-ui && npm install && npm run build
      - run: sudo apt-get update && sudo apt-get -y install alien
      - run: ./build-deb-schedule              # build package for schedule daemon
      - run: ./build-deb-web                   # build package for web interface
      - run: ./build-deb-all                   # build bundle with schedule daemon web interface
      - uses: actions/upload-artifact@v2
        with:
          name: parental-control
          path: |
            dist/*.rpm
            dist/*.deb

  build-windows-verson:
    name: Windows build
    runs-on: windows-2019
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache of Stack
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\Programs\stack
          key: ${{ runner.os }}

      - run: cd schedule-daemon && stack build --copy-bins
      - name: Prepare files for contribution
        shell: cmd
        run: .\build-windows.bat
      - name: Create installer
        uses: joncloud/makensis-action@v3.6
        with:
          arguments: "/V3"
          script-file: "parental-control.nsi"

#      - run: wget https://get.haskellstack.org/stable/windows-x86_64-installer.exe
#      -
